badword_list = ['anal',
 'anus',
 'arse',
 'ass',
 'balls',
 'ballsack',
 'bastard',
 'biatch',
 'bitch',
 'bloody',
 'blow job',
 'blowjob',
 'bollock',
 'bollok',
 'boner',
 'boob',
 'bugger',
 'bum',
 'butt',
 'buttplug',
 'clitoris',
 'cock',
 'coon',
 'crap',
 'cunt',
 'damn',
 'dick',
 'dildo',
 'dyke',
 'f u c k',
 'fag',
 'feck',
 'felching',
 'fellate',
 'fellatio',
 'flange',
 'fuck',
 'fudge packer',
 'fudgepacker',
 'God damn',
 'Goddamn',
 'hell',
 'homo',
 'jerk',
 'jizz',
 'knob end',
 'knobend',
 'labia',
 'lmao',
 'lmfao',
 'muff',
 'nigga',
 'nigger',
 'omg',
 'penis',
 'piss',
 'poop',
 'prick',
 'pube',
 'pussy',
 'queer',
 's hit',
 'scrotum',
 'sex',
 'sh1t',
 'shit',
 'slut',
 'smegma',
 'spunk',
 'tit',
 'tosser',
 'turd',
 'twat',
 'vagina',
 'wank',
 'whore',
 'wtf',
 'aandu',
 'aand',
 'amma ki chut',
 'baap ke lavde',
 'bakrichod',
 'balatkaar',
 'balatkar',
 'behanchod',
 'behen ke laude',
 'behenchod',
 'beti chod',
 'betichod',
 'bhaand me jaao',
 'bhadavya',
 'bhadva',
 'bhadve',
 'bhadwe ki nasal',
 'bhai chhod',
 'bhandve',
 'bhayee chod',
 'bhaynchod',
 'bhen chhod',
 'bhen ke lode maa chuda',
 'bhen ke lode',
 'bhikaar',
 'bhootni ke',
 'bhosad chod',
 'bhosadaaa',
 'bhosadaa',
 'bhosada',
 'bhosadchod',
 'bhosadi ke',
 'bhosadii',
 'bhosadika',
 'bhosadike',
 'bhosadiki',
 'bhosad',
 'bhosdee kay',
 'bhosdi k',
 'bhosdike',
 'bhosdi',
 'boobe',
 'bosadike',
 'bulle ke baal',
 'bulli',
 'bursungha',
 'camina',
 'cha cha chod',
 'chakke',
 'chinaal',
 'chinki',
 'chipkai ki choot ke paseene',
 'chod bhangra',
 'chod ke bal ka kida',
 'chodika',
 'chodoo',
 'chodu bhagat',
 'chodubhagat',
 'chodu',
 'chod',
 'chooche',
 'choochi',
 'choodu',
 'choot k bhoot',
 'choot k pakode',
 'choot ka paani',
 'choot ka pissu',
 'choot ke baal',
 'choot ki jhilli',
 'chootia',
 'chootiya',
 'chootiye',
 'choot',
 'chopre he randi',
 'chuche',
 'chuchi',
 'chudai khanaa',
 'chudan chudai',
 'chudasi',
 'chudpagal',
 'chut ka maindak',
 'chut ke baal',
 'chut ke dhakkan',
 'chut ke makkhan',
 'chut maarli',
 'chutadd',
 'chutad',
 'chutan',
 'chutia',
 'chutiya',
 'chutiye',
 'chut',
 'dheeli choot',
 'gaand chaat mera',
 'gaand ka khadda',
 'gaand ke dhakan',
 'gaand maar bhen chod',
 'gaand mein kida',
 'gaandfat',
 'gaandmasti',
 'gaandufad',
 'gaandu',
 'gaand',
 'gand mein louda',
 'gandi chut mein sadta hua ganda kida',
 'gandi fuddi ki gandi auladd',
 'gandit',
 'gandmasti',
 'gandoo',
 'gandu',
 'gand',
 'gashti',
 'gasti',
 'ghassa',
 'ghasti',
 'haram zaadaa',
 'harami',
 'haramzade',
 'hawas ke pujari',
 'hawas',
 'hijda',
 'hijra',
 'jhaat ke baal',
 'jhaat',
 'jhant chaatu',
 'jhant ke baal',
 'jhantu',
 'jhant',
 'jhat lahergaya',
 'jhatoo',
 'jhavadya',
 'kaala lund',
 'kaali kutti',
 'kaminey',
 'kamine',
 'kanjar',
 'kukarchod',
 'kutha sala',
 'kuthri',
 'kuthta buraanahe kandaa nahi pattaahe',
 'kutta kamina',
 'kutta',
 'kutte ki aulad',
 'kutte ki jat',
 'kutte ki olad',
 'kutte',
 'kuttiya',
 'laudu',
 'lavadya',
 'lavde ka baal',
 'lavde',
 'loda',
 'lode jesi shakal ke',
 'lode ke baal',
 'lodu',
 'lowde ka bal',
 'luhnd',
 'lund choos',
 'lund chuse',
 'lund k laddu',
 'lund khajoor',
 'lund mera muh tera',
 'lundfakir',
 'lundh',
 'lundtopi',
 'lundure',
 'lund',
 'maa ki chut',
 'maadarbhagat',
 'maadarchod',
 'maadar',
 'maal chhodna',
 'maal',
 'maa cho',
 'madar chod',
 'madarchod ke aulaad',
 'madarchod',
 'madarchoth',
 'madar',
 'mader chod',
 'mahder chod',
 'mai chod',
 'mera gota moo may lay',
 'mera mume le',
 'mere fudi kha ley',
 'meri ghand ka baal',
 'mome ka pasina chat',
 'moo may lay mera',
 'mooh mein le',
 'muttha',
 'mutth',
 'najayaz aulaad',
 'najayaz paidaish',
 'najayaz',
 'padosi ki aulaad',
 'paki',
 'pataka',
 'patakha',
 'raandichya',
 'raand',
 'rand ki moot',
 'randi baj',
 'randi ka choda',
 'randi ka larka',
 'randi ke bacche',
 'randi ke beej',
 'randi',
 'saala kutta',
 'saala',
 'saale lm',
 'saali kutti',
 'saali randi',
 'sab ka lund teri ma ki chut mein',
 'sinak se paida hua',
 'suar ki aulad',
 'suar',
 'sust lund ki padaish',
 'suvar chod',
 'suwar ki aulad',
 'suzit',
 'tatte',
 'tatti ander lele',
 'tatti',
 'tera gittha',
 'tere baap ki gaand',
 'tere maa ka bur',
 'teri behen ka bhosda faadu',
 'teri bhosri mein aag',
 'teri chute mai chuglee',
 'teri gaand me danda',
 'teri gaand mein haathi ka lund',
 'teri gand mai ghadhe ka lund',
 'teri ma bahar chud rahi he',
 'teri ma ki choot me bara sa land',
 'teri ma ki chudaye bandar se hui',
 'teri ma ko kutta chode',
 'teri ma randi',
 'teri maa ka bhosada',
 'teri maa ka bhosra',
 'teri maa ka boba chusu',
 'teri maa ke bable',
 'teri maa ke bhosade ke baal',
 'teri maa ki choot me kutte ka lavda',
 'teri maa ki choot',
 'teri maa ki chute',
 'teri maa ki chut',
 'teri maa ki sukhi bhos',
 'teri phuphi ki choot mein',
 'tharak',
 'tharki',
 'tu tera maa ka lauda',
 'tuzya aaichi kanda puchi',
 'ullu',
 'आंडू',
 'आनंद',
 'अम्मा की चूत',
 'बाप के लवड़े',
 'बकरीचोद',
 'बलातकार',
 'बालाटकर',
 'बहनचोद',
 'बहन के लौड़े',
 'बेटी चोद',
 'बेटीचोद',
 'भांड में जाओ',
 'भादव्य',
 'भादवा',
 'भादवे',
 'भडवे की नाक',
 'भाई चोद',
 'भांडवे',
 'भैनचोद',
 'बहन चोद',
 'भेन के लोडे माँ चूड़ा',
 'भेन के लोडे',
 'भिकार',
 'भूतनी के',
 'भोसड़ा चोद',
 'भोसड़ा',
 'भोसड़ाचोद',
 'भोसड़ी के',
 'भोसड़ी',
 'भोसडिका',
 'भोसदिके',
 'भोसड़ीकी',
 'भोसडाइक',
 'उल्लू',
 'बोसादिके',
 'बुल्ले के बाल',
 'बुली',
 'बरसुंघा',
 'कैमिना',
 'चा चा चोद',
 'चक्के',
 'छिनाल',
 'चिंकी',
 'चिपकाई की चूत के पसीने',
 'चोद भांगड़ा',
 'चोद के बाल का बच्चा',
 'चोदिका',
 'चोदू',
 'चोदू भगत',
 'चोदुभगत',
 'चोद',
 'चूचे',
 'चूची',
 'चोदु',
 'चोट के भूत',
 'छूट के पकोड़े',
 'चूत का पानी',
 'चूत का पिस्सू',
 'चूत के बाल',
 'चूत की झिल्ली',
 'चुटिया',
 'छुट्टियाँ',
 'चुट',
 'चोपरे वह रंडी',
 'चुदाई खाना',
 'चोदन चुदाई',
 'चुदासी',
 'चुड़पगल',
 'चुट का आदमी',
 'चूत के धक्के',
 'चूत के मक्खन',
 'चूत मारली',
 'चुटड्ड',
 'चुतड',
 'चुटन',
 'ढीली चूत',
 'गांड चाट मेरा',
 'गांड का खड़ा',
 'गांड के ढकन',
 'गांड मार बहन चोद',
 'गांड में बच्चा',
 'गांडफैट',
 'गांडमस्ती',
 'गंडुफाड',
 'गांडू',
 'गांड',
 'गांड में लौड़ा',
 'गंदी चूत में सदता हुआ गंदा बच्चा',
 'गन्दी फुद्दी की गन्दी औलाद',
 'गांडित',
 'गश्ती',
 'गस्ती',
 'घासा',
 'ग़ास्ती',
 'हराम ज़ादा',
 'हरामी',
 'हरामजादे',
 'हवस के पुजारी',
 'हवास',
 'हिजड़ा',
 'झट के बाल',
 'झाट',
 'झाँट चाटु',
 'झांट के बाल',
 'झंटू',
 'झांट',
 'झट लहरगया',
 'झाटू',
 'झावड्या',
 'काला लंड',
 'काली कुट्टी',
 'कमीने',
 'कमीन',
 'कंजर',
 'कुकरचोद',
 'कुथा साला',
 'कुथरी',
 'कुत्था बुरानाहे कांदा नहीं पताहे',
 'कुत्ता कमीना',
 'कुत्ता',
 'कुत्ते की औलाद',
 'कुत्ते की जात',
 'कुत्ते की ओलाद',
 'कुट्टे',
 'कुट्टिया',
 'लाउडू',
 'लवद्य',
 'लवड़े का बाल',
 'लवडे',
 'लोडा',
 'लोडे जेसी शकल के',
 'लोडे के बाल',
 'लोडु',
 'लोड़े का बाल',
 'लुहंड',
 'लंड चुनता है',
 'लंड चुसे',
 'लंड के लड्डू',
 'लंड खजूर',
 'लंड मेरा मुँह तेरा',
 'लंडफकीर',
 'लंड',
 'लंडटोपी',
 'लंडुरे',
 'माँ की चूत',
 'मादरभगत',
 'मादरचोद',
 'मादर',
 'माल चोदना',
 'माल',
 'माँ चो',
 'मादर चोद',
 'मादरचोद के औलाद',
 'मदारचोथ',
 'मदार',
 'महदर चोद',
 'माई चोद',
 'मेरा गोटा मू हो सकता है',
 'मेरा मुमे ले',
 'मेरे फुदी खा लेय',
 'मेरी गांड का बाल',
 'माँ का पसीना चैट',
 'मू मे ले मेरा',
 'मुहं में ले',
 'मुत्था',
 'मुथ',
 'नज़ायाज़ औलाद',
 'नज़ायाज़ पैदाइश',
 'नज़ायाज़',
 'पडोसी की औलाद',
 'पाकिस्तान',
 'पटाका',
 'पटाखा',
 'रणदिच्य',
 'रैंड',
 'रांड की लूट',
 'रंडी बाज',
 'रंडी का चोदा',
 'रंडी का लरका',
 'रंडी के बच्चे',
 'रंडी के बीज',
 'रंडी',
 'साला कुत्ता',
 'साला',
 'साले एलएम',
 'साली कुट्टी',
 'साली रंडी',
 'सबका लंड तेरी माँ की चूत में',
 'सिनाक से पेदा हुआ',
 'सुअर की औलाद',
 'सूअर',
 'सुस्त लंड की पैदाइश',
 'सुवर चोद',
 'सुवार की औलाद',
 'सुज़िट',
 'टैटे',
 'टैटी एंडर लेले',
 'टाटी',
 'तेरा गित्था',
 'तेरे बाप की गांड',
 'तेरे माँ का बुर',
 'तेरी बहन का भोसड़ा फाड़ू',
 'तेरी भोसड़ी में आग',
 'तेरी छुटे मैं चुगली',
 'तेरी गांड मैं डंडा',
 'तेरी गांड में हाथी का लंड',
 'तेरी गांड माई गधे का लंड',
 'तेरी माँ बाहर चुद रही है',
 'तेरी माँ की चूत में बारा सा लंड',
 'तेरी माँ की चुदाई बंदर से हुई',
 'तेरी माँ को कुत्ता चोदे',
 'तेरी माँ रंडी',
 'तेरी माँ का भोसड़ा',
 'तेरी माँ का बोबा चुसु',
 'तेरी माँ के बबले',
 'तेरी माँ के भोसड़े के बाल',
 'तेरी माँ की चूत में कुत्ते का लवड़ा',
 'तेरी माँ की चूत',
 'तेरी माँ की प्यारी',
 'तेरी माँ की सुखी भोस',
 'तेरी फुफी की चूत में',
 'ठरक',
 'ठरकी',
 'तू तेरा माँ का लौड़ा',
 'तुज्या आइची कांडा पुची'
 ]
